### ISSUE TITLE
Let's turn this into a portfolio showcase website

### ISSUE THREAD

**Issue by aayushdutt** [emmabostian/developer-portfolios#174]
The list of portfolios is now really large, and it's nearly impossible to look through endless list of names to find something.

Similar to [jamstackthemes](https://jamstackthemes.dev/), it will be a lot better to have the portfolios nicely organised and have a screenshot. Since [jamstackthemes](https://jamstackthemes.dev/) is MIT licenced, maybe we can build the website on top of its [source code](https://github.com/stackbithq/jamstackthemes)
This will also address the issues #83 and #135

**Comment by AmruthPillai** [comment]
I can build something like this actually, from scratch using GatsbyJS and the `gatsby-transformer-screenshot` plugin. It would mean we have to change up the way submissions are being formatted from markdown to YAML instead, but it would be worth it to have a more structured approach, one where we can put in additional data like location or individual/agency etc.

**Comment by doxsch** [comment]
I have recently created a website that uses this data. You can find it here: https://doxsch.github.io/developer-portfolios/
The website was created with gatsby and as suggested by @AmruthPillai  the plugin `gatsby-transformer-screenshot` was used.

Of course I am looking forward to pull requests from you, so that the site will be better. https://github.com/doxsch/developer-portfolios

Maybe this issue, #84  and #135 are resolved..

If I am not allowed to use this data, please tell me and I will remove the website again.

**Comment by jakeherp** [comment]
Going to close this issue since a site was built by @doxsch and an official site as part of this repo isn't planned as far as I know.
